### ISSUE TITLE
Error: EMFILE: too many open files, uv_resident_set_memory

### ISSUE THREAD

**Issue by stevenweaver** [veg/datamonkey-js#121]
The following error has occurred `23` times over the past year as of the opening of this ticket : 

```
277303 Error: EMFILE: too many open files, uv_resident_set_memory
277304     at process.memoryUsage (internal/process.js:100:5)
277305     at Object.exception.getProcessInfo (/opt/datamonkey-js/node_modules/winston/lib/winston/exception.js:33:26)
277306     at Object.exception.getAllInfo (/opt/datamonkey-js/node_modules/winston/lib/winston/exception.js:17:24)
277307     at exports.Logger.Logger._uncaughtException (/opt/datamonkey-js/node_modules/winston/lib/winston/logger.js:602:24)
277308     at emitOne (events.js:115:13)
277309     at process.emit (events.js:210:7)
277310     at process._fatalException (bootstrap_node.js:329:26)
```

We should investigate which file handlers are not being properly closed.

**Comment by markstos** [comment]
Any progress here?
